version: '3'

services:
  nudges:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src/personalised_nudges
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hack_app
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=hack
    expose:
      - 5432

volumes:
  postgres_data: