version: '3'

# docker-compose -f docker-compose.dev.yml build
# docker-compose -f docker-compose.dev.yml up -d
services:
  app:
    build: .
    container_name: hack
    environment:
      - DATABASE_URL=postgresql://hack_app:1@localhost:5432/hack
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hack_app
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=hack
